SET IDENTITY_INSERT [dbo].[SysDivision] ON;

MERGE [dbo].[SysDivision] AS TARGET
USING
(
			SELECT @Division_DHAKA		, N'DHAKA'
   UNION	SELECT @Division_CHITTAGONG , N'CHITTAGONG'
   UNION	SELECT @Divsion_RAJSHAHI	, N'RAJSHAHI'
   UNION	SELECT @Divsion_SYLHET		, N'SYLHET'
   UNION	SELECT @Divsion_BARISAL		, N'BARISAL'
   UNION	SELECT @Divsion_KHULNA		, N'KHULNA'
   UNION	SELECT @Divsion_RANGPUR		, N'RANGPUR'
   UNION	SELECT @Divsion_MYMENSINGH	, N'MYMENSINGH'

) AS SOURCE ([Id],[Name])
	ON TARGET.[Id] = SOURCE.[Id]
WHEN MATCHED THEN
	UPDATE SET
		TARGET.[Name] = SOURCE.[Name]
WHEN NOT MATCHED THEN
	INSERT([Id],[Name])
	VALUES(SOURCE.[Id],SOURCE.[Name])
;

SET IDENTITY_INSERT [dbo].[SysDivision] OFF;