SET IDENTITY_INSERT [dbo].[SysUnion] ON;

MERGE [dbo].[SysUnion] AS TARGET
USING
(
			SELECT @Union_KUSHUMHATI	, N'KUSHUMHATI'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_MAHMUDPUR		, N'MAHMUDPUR'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_MOKSEDPUR		, N'MOKSEDPUR'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_NARISHA		, N'NARISHA'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_NAYABARI		, N'NAYABARI'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_RAIPARA		, N'RAIPARA'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_SUTARPARA		, N'SUTARPARA'	, @Upazila_DHAMRAI
   UNION	SELECT @Union_BILASHPUR		, N'BILASHPUR'	, @Upazila_DHAMRAI
) AS SOURCE ([Id],[Name],[UpazilaId])
	ON TARGET.[Id] = SOURCE.[Id]
WHEN MATCHED THEN
	UPDATE SET
		TARGET.[Name] = SOURCE.[Name],
		TARGET.[UpazilaId] = SOURCE.[UpazilaId]
WHEN NOT MATCHED THEN
	INSERT([Id],[Name],[UpazilaId])
	VALUES(SOURCE.[Id],SOURCE.[Name],SOURCE.[UpazilaId])
;

SET IDENTITY_INSERT [dbo].[SysUnion] OFF;