CREATE TABLE [dbo].[ComponentType]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(256) NOT NULL,
	[NoOfMaxLoan] INT NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [UserId] NVARCHAR(128) NOT NULL, 
	[SystemDate] DATETIME NOT NULL,
    [SetDate] DATETIME NOT NULL,
	CONSTRAINT [PK_ComponentType] PRIMARY KEY ([Id])
)
