CREATE TABLE [dbo].[SysThana]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(50) NOT NULL, 
	[UnionId] INT NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [CreatedBy] NVARCHAR(256) NOT NULL DEFAULT 'ScopoMFinance', 
    [CreatedOn] DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_Thana] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Thana_Union] FOREIGN KEY ([UnionId]) REFERENCES [SysUnion]([Id])
)
