//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BranchStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BranchStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.BranchStrings", typeof(BranchStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch is added successfully.
        /// </summary>
        public static string Branch_Add_Success_Msg {
            get {
                return ResourceManager.GetString("Branch_Add_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string Branch_List_DN_BranchName {
            get {
                return ResourceManager.GetString("Branch_List_DN_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Date.
        /// </summary>
        public static string Branch_List_DN_BranchOpenDate {
            get {
                return ResourceManager.GetString("Branch_List_DN_BranchOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Branch_List_DN_BranchStatus {
            get {
                return ResourceManager.GetString("Branch_List_DN_BranchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office.
        /// </summary>
        public static string Branch_List_DN_HeadOffice {
            get {
                return ResourceManager.GetString("Branch_List_DN_HeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit Officers.
        /// </summary>
        public static string Branch_List_DN_TotalCO {
            get {
                return ResourceManager.GetString("Branch_List_DN_TotalCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Components.
        /// </summary>
        public static string Branch_List_DN_TotalComponent {
            get {
                return ResourceManager.GetString("Branch_List_DN_TotalComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Organizations.
        /// </summary>
        public static string Branch_List_DN_TotalOrg {
            get {
                return ResourceManager.GetString("Branch_List_DN_TotalOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string Branch_List_DN_TotalUser {
            get {
                return ResourceManager.GetString("Branch_List_DN_TotalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch is updated successfully.
        /// </summary>
        public static string Branch_Update_Success_Msg {
            get {
                return ResourceManager.GetString("Branch_Update_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office.
        /// </summary>
        public static string HeadOffice {
            get {
                return ResourceManager.GetString("HeadOffice", resourceCulture);
            }
        }
    }
}
