//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComponentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComponentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.ComponentStrings", typeof(ComponentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has been created successfully.
        /// </summary>
        public static string Component_Create_Success_Msg {
            get {
                return ResourceManager.GetString("Component_Create_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Component.
        /// </summary>
        public static string Component_Create_Title {
            get {
                return ResourceManager.GetString("Component_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Component.
        /// </summary>
        public static string Component_Edit_Title {
            get {
                return ResourceManager.GetString("Component_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! This component code is already been used.
        /// </summary>
        public static string Component_Edit_Validation_ComponentCodeUnavailable {
            get {
                return ResourceManager.GetString("Component_Edit_Validation_ComponentCodeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Provided component type is inactive .
        /// </summary>
        public static string Component_Edit_Validation_ComponentTypeInactive {
            get {
                return ResourceManager.GetString("Component_Edit_Validation_ComponentTypeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Code.
        /// </summary>
        public static string Component_List_DN_Code {
            get {
                return ResourceManager.GetString("Component_List_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type.
        /// </summary>
        public static string Component_List_DN_ComponentTypeName {
            get {
                return ResourceManager.GetString("Component_List_DN_ComponentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor.
        /// </summary>
        public static string Component_List_DN_DonorName {
            get {
                return ResourceManager.GetString("Component_List_DN_DonorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Component_List_DN_Duration {
            get {
                return ResourceManager.GetString("Component_List_DN_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Component_List_DN_Name {
            get {
                return ResourceManager.GetString("Component_List_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string Component_List_Title {
            get {
                return ResourceManager.GetString("Component_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &amp; Component Mapping.
        /// </summary>
        public static string Component_Map_Branch_Setup_Title {
            get {
                return ResourceManager.GetString("Component_Map_Branch_Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Code.
        /// </summary>
        public static string Component_Setup_DN_Code {
            get {
                return ResourceManager.GetString("Component_Setup_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type.
        /// </summary>
        public static string Component_Setup_DN_ComponentTypeName {
            get {
                return ResourceManager.GetString("Component_Setup_DN_ComponentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor.
        /// </summary>
        public static string Component_Setup_DN_DonorName {
            get {
                return ResourceManager.GetString("Component_Setup_DN_DonorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Component_Setup_DN_Duration {
            get {
                return ResourceManager.GetString("Component_Setup_DN_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Name.
        /// </summary>
        public static string Component_Setup_DN_Name {
            get {
                return ResourceManager.GetString("Component_Setup_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has been updated successfully.
        /// </summary>
        public static string Component_Update_Success_Msg {
            get {
                return ResourceManager.GetString("Component_Update_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Component Type.
        /// </summary>
        public static string ComponentType_Create_Title {
            get {
                return ResourceManager.GetString("ComponentType_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has been created successfully.
        /// </summary>
        public static string ComponentType_Edit_Create_Success_Msg {
            get {
                return ResourceManager.GetString("ComponentType_Edit_Create_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Component Type.
        /// </summary>
        public static string ComponentType_Edit_Title {
            get {
                return ResourceManager.GetString("ComponentType_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component has been updated succesfully.
        /// </summary>
        public static string ComponentType_Edit_Update_Success_Msg {
            get {
                return ResourceManager.GetString("ComponentType_Edit_Update_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Name.
        /// </summary>
        public static string ComponentType_List_DN_Name {
            get {
                return ResourceManager.GetString("ComponentType_List_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Loan No.
        /// </summary>
        public static string ComponentType_List_DN_NoOfMaxLoan {
            get {
                return ResourceManager.GetString("ComponentType_List_DN_NoOfMaxLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type.
        /// </summary>
        public static string ComponentType_List_Title {
            get {
                return ResourceManager.GetString("ComponentType_List_Title", resourceCulture);
            }
        }
    }
}
