//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.EmployeeStrings", typeof(EmployeeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employee_List_DN_Address {
            get {
                return ResourceManager.GetString("Employee_List_DN_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Employee_List_DN_Branch {
            get {
                return ResourceManager.GetString("Employee_List_DN_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string Employee_List_DN_EmployeeName {
            get {
                return ResourceManager.GetString("Employee_List_DN_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        public static string Employee_List_DN_EmployeeNo {
            get {
                return ResourceManager.GetString("Employee_List_DN_EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Type.
        /// </summary>
        public static string Employee_List_DN_EmployeeType {
            get {
                return ResourceManager.GetString("Employee_List_DN_EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Employee_List_DN_Gender {
            get {
                return ResourceManager.GetString("Employee_List_DN_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Employee_List_DN_IsActive {
            get {
                return ResourceManager.GetString("Employee_List_DN_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Officer.
        /// </summary>
        public static string Employee_List_DN_IsCO {
            get {
                return ResourceManager.GetString("Employee_List_DN_IsCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string Employee_List_DN_JoiningDate {
            get {
                return ResourceManager.GetString("Employee_List_DN_JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Employee_List_DN_PhoneNo {
            get {
                return ResourceManager.GetString("Employee_List_DN_PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Employee_List_DN_Remarks {
            get {
                return ResourceManager.GetString("Employee_List_DN_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resigning Date.
        /// </summary>
        public static string Employee_List_DN_ResignDate {
            get {
                return ResourceManager.GetString("Employee_List_DN_ResignDate", resourceCulture);
            }
        }
    }
}
