//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.OrganizationStrings", typeof(OrganizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Organization Added Successfully.
        /// </summary>
        public static string Organization_Edit_Add_Success_Msg {
            get {
                return ResourceManager.GetString("Organization_Edit_Add_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization.
        /// </summary>
        public static string Organization_Edit_Add_Title {
            get {
                return ResourceManager.GetString("Organization_Edit_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Organization_Edit_DN_IsActive {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Category.
        /// </summary>
        public static string Organization_Edit_DN_OrgCategory {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Loan Collection Date.
        /// </summary>
        public static string Organization_Edit_DN_OrgFirstLoanColcDate {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgFirstLoanColcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Savings Collection Date.
        /// </summary>
        public static string Organization_Edit_DN_OrgFirstSavColcDate {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgFirstSavColcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Organization_Edit_DN_OrgGender {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Collection Option.
        /// </summary>
        public static string Organization_Edit_DN_OrgLoanColcOption {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgLoanColcOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string Organization_Edit_DN_OrgName {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization No.
        /// </summary>
        public static string Organization_Edit_DN_OrgNo {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Collection Option.
        /// </summary>
        public static string Organization_Edit_DN_OrgSavColcOption {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgSavColcOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date.
        /// </summary>
        public static string Organization_Edit_DN_OrgSetupDate {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgSetupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string Organization_Edit_DN_OrgVillage {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization has been edited successfully.
        /// </summary>
        public static string Organization_Edit_Update_Success_Msg {
            get {
                return ResourceManager.GetString("Organization_Edit_Update_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Organization.
        /// </summary>
        public static string Organization_Edit_Update_Title {
            get {
                return ResourceManager.GetString("Organization_Edit_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization No Already Exists.
        /// </summary>
        public static string Organization_Edit_Validation_OrgNoUnavailable {
            get {
                return ResourceManager.GetString("Organization_Edit_Validation_OrgNoUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Organization_List_DN_IsActive {
            get {
                return ResourceManager.GetString("Organization_List_DN_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Organization_List_DN_OrgCategory {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Loan Collection Date.
        /// </summary>
        public static string Organization_List_DN_OrgFirstLoanColcDate {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgFirstLoanColcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Savings Collection Date.
        /// </summary>
        public static string Organization_List_DN_OrgFirstSavColcDate {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgFirstSavColcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Organization_List_DN_OrgGender {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Collection Option.
        /// </summary>
        public static string Organization_List_DN_OrgLoanColcOption {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgLoanColcOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string Organization_List_DN_OrgName {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization No.
        /// </summary>
        public static string Organization_List_DN_OrgNo {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Collection Option.
        /// </summary>
        public static string Organization_List_DN_OrgSavColcOption {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgSavColcOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date.
        /// </summary>
        public static string Organization_List_DN_OrgSetupDate {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgSetupDate", resourceCulture);
            }
        }
    }
}
