//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.OrganizationStrings", typeof(OrganizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Officer.
        /// </summary>
        public static string Organization_CO_DN_CreditOfficer {
            get {
                return ResourceManager.GetString("Organization_CO_DN_CreditOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit officer has been mapped successfully.
        /// </summary>
        public static string Organization_CO_Map_Successfull_Msg {
            get {
                return ResourceManager.GetString("Organization_CO_Map_Successfull_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one center.
        /// </summary>
        public static string Organization_CO_Validation_EmptyOrganizationList {
            get {
                return ResourceManager.GetString("Organization_CO_Validation_EmptyOrganizationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center {0} is Invalid.
        /// </summary>
        public static string Organization_CO_Validation_InvalidOrg {
            get {
                return ResourceManager.GetString("Organization_CO_Validation_InvalidOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center {0} has already a credit officer.
        /// </summary>
        public static string Organization_CO_Validation_OrgHasCO {
            get {
                return ResourceManager.GetString("Organization_CO_Validation_OrgHasCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Wise Credit Officer Mapping.
        /// </summary>
        public static string Organization_Credit_Officer_Title {
            get {
                return ResourceManager.GetString("Organization_Credit_Officer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center has been deleted successfully.
        /// </summary>
        public static string Organization_Delete_Success_Msg {
            get {
                return ResourceManager.GetString("Organization_Delete_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Center has been added successfully.
        /// </summary>
        public static string Organization_Edit_Add_Success_Msg {
            get {
                return ResourceManager.GetString("Organization_Edit_Add_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Center.
        /// </summary>
        public static string Organization_Edit_Add_Title {
            get {
                return ResourceManager.GetString("Organization_Edit_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Organization_Edit_DN_IsActive {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date.
        /// </summary>
        public static string Organization_Edit_DN_MeetingDate {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Frequency.
        /// </summary>
        public static string Organization_Edit_DN_MeetingFrequency {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_MeetingFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Category.
        /// </summary>
        public static string Organization_Edit_DN_OrgCategory {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Organization_Edit_DN_OrgGender {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        public static string Organization_Edit_DN_OrgName {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center No.
        /// </summary>
        public static string Organization_Edit_DN_OrgNo {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date.
        /// </summary>
        public static string Organization_Edit_DN_OrgSetupDate {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgSetupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string Organization_Edit_DN_OrgVillage {
            get {
                return ResourceManager.GetString("Organization_Edit_DN_OrgVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center has been edited successfully.
        /// </summary>
        public static string Organization_Edit_Update_Success_Msg {
            get {
                return ResourceManager.GetString("Organization_Edit_Update_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Center.
        /// </summary>
        public static string Organization_Edit_Update_Title {
            get {
                return ResourceManager.GetString("Organization_Edit_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center No Already Exists.
        /// </summary>
        public static string Organization_Edit_Validation_OrgNoUnavailable {
            get {
                return ResourceManager.GetString("Organization_Edit_Validation_OrgNoUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Center.
        /// </summary>
        public static string Organization_List_Create_Button {
            get {
                return ResourceManager.GetString("Organization_List_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Officer.
        /// </summary>
        public static string Organization_List_DN_CreditOfficer {
            get {
                return ResourceManager.GetString("Organization_List_DN_CreditOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Organization_List_DN_IsActive {
            get {
                return ResourceManager.GetString("Organization_List_DN_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date.
        /// </summary>
        public static string Organization_List_DN_MeetingDate {
            get {
                return ResourceManager.GetString("Organization_List_DN_MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Frequency.
        /// </summary>
        public static string Organization_List_DN_MeetingFrequency {
            get {
                return ResourceManager.GetString("Organization_List_DN_MeetingFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Organization_List_DN_OrgCategory {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Organization_List_DN_OrgGender {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        public static string Organization_List_DN_OrgName {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center No.
        /// </summary>
        public static string Organization_List_DN_OrgNo {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Date.
        /// </summary>
        public static string Organization_List_DN_OrgSetupDate {
            get {
                return ResourceManager.GetString("Organization_List_DN_OrgSetupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center List.
        /// </summary>
        public static string Organization_List_Title {
            get {
                return ResourceManager.GetString("Organization_List_Title", resourceCulture);
            }
        }
    }
}
