//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScopoMFinance.Localization.ProductStrings", typeof(ProductStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string Ln_Product_List_DN_Code {
            get {
                return ResourceManager.GetString("Ln_Product_List_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        public static string Ln_Product_List_DN_IntRate {
            get {
                return ResourceManager.GetString("Ln_Product_List_DN_IntRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Ln_Product_List_DN_Name {
            get {
                return ResourceManager.GetString("Ln_Product_List_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string Ln_Product_Setup_DN_Code {
            get {
                return ResourceManager.GetString("Ln_Product_Setup_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        public static string Ln_Product_Setup_DN_IntRate {
            get {
                return ResourceManager.GetString("Ln_Product_Setup_DN_IntRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Ln_Product_Setup_DN_Name {
            get {
                return ResourceManager.GetString("Ln_Product_Setup_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already been used.
        /// </summary>
        public static string Ln_Product_Setup_Validation_DuplicateCode {
            get {
                return ResourceManager.GetString("Ln_Product_Setup_Validation_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string Sav_Product_List_DN_Code {
            get {
                return ResourceManager.GetString("Sav_Product_List_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        public static string Sav_Product_List_DN_IntRate {
            get {
                return ResourceManager.GetString("Sav_Product_List_DN_IntRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Sav_Product_List_DN_Name {
            get {
                return ResourceManager.GetString("Sav_Product_List_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string Sav_Product_Setup_DN_Code {
            get {
                return ResourceManager.GetString("Sav_Product_Setup_DN_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        public static string Sav_Product_Setup_DN_IntRate {
            get {
                return ResourceManager.GetString("Sav_Product_Setup_DN_IntRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Sav_Product_Setup_DN_Name {
            get {
                return ResourceManager.GetString("Sav_Product_Setup_DN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already been used.
        /// </summary>
        public static string Sav_Product_Setup_Validation_DuplicateCode {
            get {
                return ResourceManager.GetString("Sav_Product_Setup_Validation_DuplicateCode", resourceCulture);
            }
        }
    }
}
