//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccDayCloseProgress
    {
        public int Id { get; set; }
        public int DayCloseProcessId { get; set; }
        public int DayOpenCloseId { get; set; }
        public int Status { get; set; }
    
        public virtual AccDayCloseProcess AccDayCloseProcess { get; set; }
        public virtual AccDayOpenClose AccDayOpenClose { get; set; }
    }
}
