//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccDayOpenClose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccDayOpenClose()
        {
            this.AccDayCloseProgresses = new HashSet<AccDayCloseProgress>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public bool CloseRequest { get; set; }
        public bool IsClosed { get; set; }
        public string CloseRequestBy { get; set; }
        public Nullable<System.DateTime> CloseRequestAt { get; set; }
        public System.DateTime OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccDayCloseProgress> AccDayCloseProgresses { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
