//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.OrgCreditOfficers = new HashSet<OrgCreditOfficer>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public string OrganizationNo { get; set; }
        public string OrganizationName { get; set; }
        public int OrgCategoryId { get; set; }
        public int GenderId { get; set; }
        public System.DateTime SetupDate { get; set; }
        public int LoanColcOption { get; set; }
        public int SavColcOption { get; set; }
        public System.DateTime FirstLoanColcDate { get; set; }
        public System.DateTime FirstSavColcDate { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual SysGender SysGender { get; set; }
        public virtual SysColcOption SysColcOption { get; set; }
        public virtual OrgCategory OrgCategory { get; set; }
        public virtual Project Project { get; set; }
        public virtual SysColcOption SysColcOption1 { get; set; }
        public virtual SysVillage SysVillage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgCreditOfficer> OrgCreditOfficers { get; set; }
    }
}
