//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoMFinance.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginAudit
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOutTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
